#theme: jekyll-theme-cayman
#theme: jekyll-theme-midnight
#theme: jekyll-theme-slate
#theme: jekyll-theme-minimal
remote_theme: double-great/theme@main
title: メモ
description: メモ

plugins:
- jekyll-remote-theme

toc:
    enabled: true